micronaut:
    application:
        name: test-java

    #Uncomment to set server port
    server:
        port: 8081
redis:
    uri: "redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}"
---
consul:
    client:
        registration:
            enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"